services:
  - name: chat-server
    type: web
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free

  - name: chat-client
    type: web
    env: static
    rootDir: .
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
